# Generated by Django 2.0.1 on 2018-01-05 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20180105_1600'),
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, editable=False, max_length=500)),
                ('slug', models.SlugField(blank=True, help_text='Customizable slug. Defaults to Org slug without stopwords.', max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('short_label', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_code', models.CharField(max_length=3, unique=True)),
                ('aggregate_candidates', models.BooleanField(default=True, help_text="Determines whether to globally aggregate vote totals of this         party's candidates during an election.")),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='political_party', to='entity.Organization')),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
    ]
