# Generated by Django 2.0.1 on 2018-01-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='slug',
            field=models.SlugField(blank=True, help_text='Customizable slug. Defaults to slugged Org name.', max_length=255),
        ),
    ]
